# -*- coding: utf-8 -*-
"""2.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dp1rKsHwnl8g11Q6c5y3YC75Op7EQpar
"""

class Persona:

    def __init__(self, nombre, apellidos, numero_documento_identidad, año_nacimiento):
        self.nombre = nombre
        self.apellidos = apellidos
        self.numero_documento_identidad = numero_documento_identidad
        self.año_nacimiento = año_nacimiento

    def imprimir_datos(self):

        print(f"Nombre: {self.nombre}")
        print(f"Apellidos: {self.apellidos}")
        print(f"Número de documento: {self.numero_documento_identidad}")
        print(f"Año de nacimiento: {self.año_nacimiento}\n")

if __name__ == "__main__":

    persona1 = Persona("Pedro", "Perez", "1053121010", 1998)
    persona2 = Persona("Luis", "León", "1053223344", 2001)

    persona1.imprimir_datos()
    persona2.imprimir_datos()